print("ScriptLoader starting")
source("R/Configuration.R")
source("R/Libraries.R")
source("R/Util.R")
source("R/MongoDB.R")
source("R/ui/UI.R")
source("R/Server.R")
source("R/CsvData.R")
source("R/DeepLearning.R")